services:
  - type: web
    name: app-backend
    branch: main
    runtime: go
    # Build and deploy `app-backend` if any files change
    # within the `backend` or `community/docker` folders.
    rootDir: backend
    buildCommand: go build -o app .
    startCommand: ./app
    buildFilter:
      paths:
        - community/docker/**